[package]
name = "frz"
version = "0.4.0"
edition = "2024"
description = "TUI fuzzy finder revolving around tabular data, utilising Saghen's Frizbee crate for matching"
license = "MIT"
homepage = "https://github.com/Alb-O/frz"
repository = "https://github.com/Alb-O/frz"
authors = ["Albert O'Shea"]

[features]
default = []

[dependencies]
ratatui = "0.29"
frizbee = { version = "0.6" }
anyhow = "1.0"
ignore = "0.4"
throbber-widgets-tui = "0.9"
clap = { version = "4.5", features = ["derive", "env"] }
thiserror = "2.0"
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-width = "0.2"
tui-textarea = "0.7"
unicode-truncate = "2"
indexmap = "2.12"
toml = "0.9"
include_dir = "0.7"

[dev-dependencies]
tempfile = "3.23"
